spring:
  cloud:
    stream:
      bindings:
        sendTransaction-out-0:
          destination: t1_demo_client_transactions
          content-type: application/json

  application:
    name: TransactionService

server:
  port: 8081
