spring:
  cloud:
    stream:
      bindings:
        sendTransaction-out-0:
          destination: t1_demo_client_transactions
          content-type: application/json

  application:
    name: TransactionService

server:
  port: 8081

logging:
  level:
    root: debug
  file:
    name: logs/logs.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%M] - %msg%n"